# Generated by Django 4.1.5 on 2023-03-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='itemquestionresponse',
            constraint=models.UniqueConstraint(fields=('category', 'question', 'item'), name='pk_question_response_item'),
        ),
    ]
