# Generated by Django 4.1.5 on 2023-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemquestionresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositpoint',
            name='location',
        ),
        migrations.AddField(
            model_name='depositpoint',
            name='latitude',
            field=models.FloatField(default=12.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositpoint',
            name='longitude',
            field=models.FloatField(default=14.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='image_for_display',
            field=models.ImageField(blank=True, null=True, upload_to='display/'),
        ),
    ]
