# Generated by Django 4.1.5 on 2023-04-12 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_visitor_remove_user_is_visitor'),
        ('core', '0004_remove_item_found_location_remove_item_lost_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor'),
        ),
    ]
