# Generated by Django 4.1.5 on 2023-04-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_added_by_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item Categories'},
        ),
    ]
