# Generated by Django 4.1.5 on 2023-04-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositpoint',
            name='image_for_display',
            field=models.ImageField(blank=True, null=True, upload_to='display/'),
        ),
    ]
