# Generated by Django 4.2 on 2023-04-24 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_depositpoint_image_for_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.AddField(
            model_name='depositpoint',
            name='close_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositpoint',
            name='open_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositpointadministration',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='deposit_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.depositpoint'),
        ),
        migrations.AddField(
            model_name='item',
            name='found_location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lost_location_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemquestion',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itemquestiontag'),
        ),
    ]
