# Generated by Django 4.2 on 2023-04-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_depositpoint_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reclamation',
        ),
    ]
