# Generated by Django 4.2 on 2023-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
