# Generated by Django 4.2 on 2023-05-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_itemcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='icon_for_map',
            field=models.ImageField(blank=True, null=True, upload_to='icons_map/'),
        ),
    ]
